#124 add Monoid formula
fontist/formulas pull request #145
Opened 2023-03-18 20:18 UTC by CAMOBAP

- #124

2023-03-19 08:12 UTC, ronaldtse requested changes
Can we add the homepage to the formula? Thanks!

2023-03-19 16:19 UTC, CAMOBAP commented
> Can we add the homepage to the formula? Thanks!

Done

2023-03-20 00:58 UTC, ronaldtse requested changes

2023-03-20 00:58 UTC, ronaldtse commented on Formulas/monoid.yml
> +copyright: Copyright (c) 2016, Andreas Larsen
Let's change this to what the README provides:
> Copyright (c) 2015, Andreas Larsen and contributors.

2023-03-20 00:59 UTC, ronaldtse commented
@CAMOBAP Given that many open source fonts have open source repositories, maybe we should add a metadata attribute that tells people where the font source is at? Thoughts?

2023-03-20 06:15 UTC, CAMOBAP commented
> @CAMOBAP Given that many open source fonts have open source repositories, maybe we should add a metadata attribute that tells people where the font source is at? Thoughts?

Good idea, I think we can add `source_repository`/`sources`/`repository` after `homepage` property

2023-03-20 06:44 UTC, ronaldtse approved these changes

2023-03-20 06:44 UTC, ronaldtse commented
Thanks @CAMOBAP ! Feel free to merge anytime.

2023-03-20 07:16 UTC, merged